name: HoloQuiz
version: 3.8.2
main: benloti.holoquiz.HoloQuiz
description: A fun little plugin designed to send Trivia or Math questions, with some Hololive Easter Eggs
author: Benloti, together with me, myself and I. And ChatGPT my beloved.
website: https://github.com/BenjaminPoh/HoloQuiz2
api-version: '1.19'
softdepend: [Vault, CMILib, CMI]
commands:
  HoloQuiz:
    description: HoloQuiz related commands.
    usage: "/HoloQuiz help for more information!"
permissions:
  HoloQuiz.admin:
    description: Allow access to admin commands
    default: op
  HoloQuiz.alert:
    description: Allow access to an alert before the next question is sent
  HoloQuiz.viewSourceEarly:
    description: The source can be viewed with /holoquiz info, even for unanswered questions