name: HoloQuiz2
version: '${project.version}'
main: benloti.holoquiz2.HoloQuiz2
api-version: '1.19'
commands:
  HoloQuiz:
    info:
      description: Displays information related to the current Question
      usage: /HoloQuiz info
      aliases: holoquiz info
    peko:
      description: PEKO PEKO PEKO
      usage: /HoloQuiz peko
      aliases: holoquiz peko