name: HoloQuiz
version: 1.3.0
main: benloti.holoquiz.HoloQuiz
description: A fun little plugin designed to send Trivia questions, with some Hololive Easter Eggs
author: Me myself and I. And ChatGPT my beloved.
website: https://github.com/BenjaminPoh/HoloQuiz2
api-version: '1.19'
softdepend: [Vault, CMILib, CMI]
commands:
  HoloQuiz:
    description: HoloQuiz related commands.
    usage: "/HoloQuiz help for more information!"
permissions:
  HoloQuiz.admin:
    description: Allow access to admin commands
    default: op
  