# Plugin Config
Interval: 10
GameMode: Trivia
#CheatingChecker: true
#CheatingTimer: 0.5
#CountAsCorrect: false
#CommandToPerform:

# Leaderboard Config
LeaderboardSize: 10
LeaderboardMinQuestionsNeeded: 3

# Easter Eggs!
EasterEggs: true

# Rewards!



