# Plugin Config
EnableOnStart: true
PluginPrefix: "&7[{#13A7DE>}HoloQuiz{#21C7FF<}&7] "

# Trivia Config
Interval: 300
GameMode: Trivia
Cheats:
  CheatingChecker: true
  CheatingTimer: 0.5
  CountAsCorrect: false
  CommandToPerform:
    - "msg [player] How did you answer so quickly? Cheats? >:("

# Leaderboard Config
LeaderboardSize: 10
LeaderboardMinQuestionsNeeded: 50

# Easter Eggs!
EasterEggs: true



