name: HoloQuiz
version: '1.0-SNAPSHOT'
main: benloti.holoquiz.HoloQuiz
api-version: '1.19'
softdepend: [Vault, CMILib, CMI]
commands:
  HoloQuiz:
    info:
      description: Displays information related to the current Question
      usage: /HoloQuiz info
      aliases: holoquiz info
    peko:
      description: PEKO PEKO PEKO
      usage: /HoloQuiz peko
      aliases: holoquiz peko
permissions:
  HoloQuiz.admin:
    description: Allow access to admin commands
    default: op
  